import { pipeline, env } from "https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.7.2/+esm";
env.allowLocalModels=false;env.useBrowserCache=true;
const MODEL="onnx-community/mobilenet_v2_1.0_224-plant-disease-identification-ONNX";
const $=s=>document.querySelector(s);let file=null,model=null;
const guidance={"Apple___Apple_scab":"Remove infected fallen leaves and improve canopy airflow. Follow locally approved disease-control guidance.","Apple___Black_rot":"Prune infected tissue and mummified fruit and improve orchard sanitation.","Potato___Early_blight":"Manage infected residue, rotate crops and follow locally approved fungicide guidance.","Potato___Late_blight":"Act quickly, improve ventilation and follow local late-blight alerts and approved treatment guidance.","Tomato___Early_blight":"Remove lower infected leaves, improve airflow and reduce soil splash.","Tomato___Late_blight":"Separate affected material, improve airflow and follow local late-blight alerts.","Tomato___Bacterial_spot":"Use clean planting material, avoid overhead irrigation and remove severely infected tissue.","Tomato___Leaf_Mold":"Increase ventilation and reduce humidity/leaf wetness.","Tomato___Septoria_leaf_spot":"Remove infected lower leaves, mulch to reduce soil splash and improve airflow.","Tomato___Tomato_Yellow_Leaf_Curl_Virus":"Manage whitefly vectors and use resistant varieties where available.","Tomato___Tomato_mosaic_virus":"Remove infected plants/tools from production areas and sanitize equipment.","healthy":"No disease pattern was classified. Continue routine scouting, balanced nutrition, irrigation management and sanitation."};
const pretty=s=>s.replaceAll("___"," — ").replaceAll("_"," ").replaceAll("(","").replaceAll(")","").trim(),crop=s=>s.split("___")[0].replaceAll("_"," ");
async function getModel(){if(!model){$("#status").textContent="Loading the trained plant-disease model for the first scan…";model=await pipeline("image-classification",MODEL,{dtype:"q8"})}return model}
function select(f){if(!f||!f.type.startsWith("image/")){$("#status").textContent="Please choose an image file.";return}file=f;$("#preview").src=URL.createObjectURL(f);$("#preview").hidden=false;$("#uploadView").hidden=true;$("#actions").hidden=false;$("#result").hidden=true;$("#status").textContent="Image ready. Use one clear leaf for best results."}
$("#browseBtn").onclick=()=>$("#fileInput").click();$("#fileInput").onchange=e=>select(e.target.files[0]);$("#dropzone").onclick=e=>{if(!e.target.closest("button"))$("#fileInput").click()};["dragenter","dragover"].forEach(x=>$("#dropzone").addEventListener(x,e=>{e.preventDefault();$("#dropzone").classList.add("drag")}));["dragleave","drop"].forEach(x=>$("#dropzone").addEventListener(x,e=>{e.preventDefault();$("#dropzone").classList.remove("drag")}));$("#dropzone").addEventListener("drop",e=>select(e.dataTransfer.files[0]));
$("#clearBtn").onclick=()=>{file=null;$("#fileInput").value="";$("#preview").hidden=true;$("#uploadView").hidden=false;$("#actions").hidden=true;$("#result").hidden=true;$("#status").textContent=""};
$("#scanBtn").onclick=async()=>{if(!file)return;$("#scanBtn").disabled=true;$("#scanBtn").textContent="Analyzing…";try{const out=await (await getModel())($("#preview").src,{topk:3}),top=out[0],conf=top.score,label=top.label;$("#diseaseName").textContent=conf<.60?"Uncertain result — retake the photo":pretty(label);$("#cropName").textContent=conf<.60?"The model is not confident enough to name a disease.":"Crop: "+crop(label);$("#confidenceBadge").textContent=Math.round(conf*100)+"% model confidence";$("#description").textContent=conf<.60?"The image may be unclear, outside the supported classes, or unlike the model's training images. Try a close, well-lit photo of one leaf.":"AI screening result: "+pretty(label)+". This is not a confirmed diagnosis.";$("#solution").textContent=conf<.60?"Retake the image with one leaf filling most of the frame and minimal background. If symptoms persist, consult an agronomist.":(guidance[label]||"Confirm the result in the field and follow local integrated pest-management guidance.");$("#warning").textContent="Top model results: "+out.map(x=>pretty(x.label)+" ("+Math.round(x.score*100)+"%)").join(" · ");$("#result").hidden=false;$("#result").scrollIntoView({behavior:"smooth"})}catch(e){console.error(e);$("#status").textContent="Model loading/analysis failed. Refresh and check your internet connection."}finally{$("#scanBtn").disabled=false;$("#scanBtn").textContent="🔍 Detect disease"}};
